import React from 'react';
import './blog.css';
import Link from 'next/link';

export default function BlogPage() {
  const dummyPosts = [
    {
      id: 1,
      title: "How to Build a Transformer from Scratch in Python",
      date: "Oct 25, 2026",
      readTime: "8 min read",
      excerpt: "Deep dive into the attention mechanism that powers LLMs. We break down the math behind queries, keys, and values before writing the code.",
      author: "Aditi Rao",
      role: "AI Core Member",
      image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=2940&auto=format&fit=crop"
    },
    {
      id: 2,
      title: "Event Recap: The Discrete Math Showdown",
      date: "Nov 5, 2026",
      readTime: "4 min read",
      excerpt: "Last weekend, 50 students gathered to solve complex graph theory problems. Here are the winning proofs and strategies used.",
      author: "Brahmagupta System",
      role: "AI Generated Report",
      image: "https://images.unsplash.com/photo-1632516643720-e7f5d4d62327?q=80&w=2940&auto=format&fit=crop"
    },
    {
      id: 3,
      title: "Understanding Topological Data Analysis",
      date: "Nov 12, 2026",
      readTime: "12 min read",
      excerpt: "TDA is revolutionizing how we understand the shape of high-dimensional datasets. Let's explore persistent homology.",
      author: "Dr. Arvind Ramesh",
      role: "Faculty Advisor",
      image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=2940&auto=format&fit=crop"
    }
  ];

  return (
    <div className="blog-wrapper">
      <div className="blog-hero animate-fade-in">
        <h1 className="blog-title">Knowledge Archive</h1>
        <p className="blog-subtitle">
          Original essays, tutorials, and automated event recaps generated by the Brahmagupta Club ecosystem.
        </p>
      </div>

      <div className="container px-4">
        <div className="blog-grid animate-fade-in" style={{ animationDelay: '0.2s' }}>
          {dummyPosts.map(post => (
            <Link href={`/blog/${post.id}`} key={post.id} className="blog-card" style={{ textDecoration: 'none' }}>
              <div className="blog-image-wrapper">
                <img src={post.image} alt={post.title} />
              </div>
              <div className="blog-meta">
                <span>{post.date}</span>
                <span>•</span>
                <span>{post.readTime}</span>
              </div>
              <h2 className="blog-post-title">{post.title}</h2>
              <p className="blog-excerpt">{post.excerpt}</p>
              
              <div className="blog-author">
                <div className="author-avatar flex items-center justify-center bg-gray-200">
                  <span style={{color: 'var(--color-primary)', fontWeight: 'bold'}}>{post.author.charAt(0)}</span>
                </div>
                <div className="author-info">
                  <span className="author-name">{post.author}</span>
                  <span className="author-role">{post.role}</span>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
